services:
  # Main NextJS frontend app
  nextjs:
    build:
      target: dev
      args:
        NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITEKEY: $NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITEKEY
    environment:
      # Server
      PORT: 3000
      NEXT_INTERNAL_API_URL: http://host.docker.internal:4000/api
      # Next Auth
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: BL0fViv5sZ4XAjrNLqyQvf1ctwHPafwzRHtnPYAQlAU
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  # Main Phoenix backend app
  phoenix:
    build:
      target: dev
    environment:
      # Phoenix configuration
      PHX_PORT: 4000
      PHX_HOST: localhost
      PHX_CONSUMER_URL: http://localhost:3000
      PHX_SECRET_KEY_BASE: 6RM4jaPQV7OeYsZ74E7GHy72a1GXc5F8GKjBKjjFP1OYiMN
      # Postgrex configuration
      POSTGREX_TIMEOUT: $POSTGREX_TIMEOUT
      # Google Idp configuration
      GOOGLE_OPENID_CONFIG_URL: https://accounts.google.com/.well-known/openid-configuration
      GOOGLE_OAUTH2_CERTS_URL: https://www.googleapis.com/oauth2/v2/certs
      # Ecto configuration
      PGDATABASE: richard_burton_dev
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"

  # Backend database
  db:
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: richard_burton_dev
      PGPORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  frontend:
  backend:
