name: Deploy to IFRS
on:
  push:
    branches:
      - main
jobs:
  DeployFrontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.IFRS_SSH_KEY }}
          known_hosts: ${{ secrets.IFRS_SSH_HOST }}
          if_key_exists: fail
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: export TZ=America/Sao_Paulo
      - run: git config --global user.email "ghactions@wyeworks.com"
      - run: git config --global user.name "GitHub Actions from WyeWorks"
      - run: git remote add ifrs-frontend git@gitlab.com:ifrscanoas/richard-burton/frontend.git
      - run: git fetch ifrs-frontend
      # Splits the repo so we can push only the frontend folder
      - run: git subtree split -P frontend -b stage-release
      - run: git checkout stage-release
      # Squashes the whole branch into a single temporary commit
      - run: git reset --soft ifrs-frontend/stage
      - run: git add -A
      - run: git restore --staged .gitignore Dockerfile .dockerignore .gitlab-ci.yml .ci '*gitkeep'
      - run: git diff-index --quiet HEAD || git commit -m "Release to Stage `TZ=America/Sao_Paulo date '+%d %b %Y %T São Paulo (UTC%Z)'`"
      - run: git push -f ifrs-frontend stage-release

  DeployBackend:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.IFRS_SSH_KEY }}
          known_hosts: ${{ secrets.IFRS_SSH_HOST }}
          if_key_exists: fail
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: export TZ=America/Sao_Paulo
      - run: git config --global user.email "ghactions@wyeworks.com"
      - run: git config --global user.name "GitHub Actions from WyeWorks"
      - run: git remote add ifrs-backend git@gitlab.com:ifrscanoas/richard-burton/backend.git
      - run: git fetch ifrs-backend
      # Splits the repo so we can push only the backend folder
      - run: git subtree split -P backend -b stage-release
      - run: git checkout stage-release
      # Squashes the whole branch into a single temporary commit
      - run: git reset --soft ifrs-backend/stage
      - run: git add -A
      - run: git restore --staged .gitignore Dockerfile .dockerignore .gitlab-ci.yml .ci '*gitkeep'
      - run: git diff-index --quiet HEAD || git commit -m "Release to Stage `TZ=America/Sao_Paulo date '+%d %b %Y %T São Paulo (UTC%Z)'`" --allow-empty
      - run: git push -f ifrs-backend stage-release
