name: Run backend app linter
on: push
jobs:
  Credo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: backend/.tool-versions
      - run: touch config/dev.secrets.exs
      - run: echo -e "import Config\nconfig :richard_burton, []" >> config/dev.secrets.exs
      - run: mix deps.get
      - run: mix credo
