name: Run frontend app compiler
on: push
jobs:
  NextJS:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
